name: CI

on:
  push:
    branches:
      - main  # or 'master' depending on your repo
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # change to match your project's version

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        # pip install pytest  # or any test framework you're using

    - name: Run tests
      run: |
        python3 -m pytest  # or any command that runs your tests
